# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('category', models.CharField(choices=[('WEIGHT', 'Weight'), ('LENGTH', 'Length'), ('VOLUME', 'Volume'), ('QUANTITY', 'Quantity'), ('TIME', 'Time'), ('AREA', 'Area')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='godowns', to='company.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.godown')),
            ],
            options={
                'verbose_name_plural': 'Godowns',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='company.currency')),
            ],
            options={
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_stock_item', models.BooleanField(default=True, help_text='Whether this item tracks stock or is a service')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Stock Items',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Stock Batches',
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='inventory.pricelist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Item Prices',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive for inward, negative for outward (or use godowns)', max_digits=14)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per unit for valuation', max_digits=14)),
                ('movement_date', models.DateField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('from_godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outward_movements', to='inventory.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
                ('to_godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_movements', to='inventory.godown')),
                ('voucher', models.ForeignKey(help_text='Every movement is tied to a voucher', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
            },
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['company', 'code'], name='inventory_g_company_4e086a_idx'),
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['company', 'is_active'], name='inventory_g_company_b731f7_idx'),
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['company', 'created_at'], name='inventory_g_company_1cb865_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='godown',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['company', 'is_default'], name='inventory_p_company_af6469_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['company', 'valid_from', 'valid_to'], name='inventory_p_company_c118c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['company', 'created_at'], name='inventory_p_company_175593_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['company', 'item', 'batch_number'], name='inventory_s_company_788136_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['company', 'exp_date'], name='inventory_s_company_3b0063_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['company', 'created_at'], name='inventory_s_company_cc68d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('company', 'item', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='itemprice',
            index=models.Index(fields=['item', 'price_list', 'valid_from'], name='inventory_i_item_id_b94f71_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'item', 'movement_date'], name='inventory_s_company_9b9a62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'to_godown', 'item'], name='inventory_s_company_181910_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'from_godown', 'item'], name='inventory_s_company_c983fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['voucher'], name='inventory_s_voucher_900307_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'created_at'], name='inventory_s_company_7bc174_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'sku'], name='inventory_s_company_d99bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'is_active'], name='inventory_s_company_d501b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'created_at'], name='inventory_s_company_3403ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('company', 'sku')},
        ),
    ]
