# Generated by Django 5.1.6 on 2025-12-25 08:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, help_text='Physical quantity available in godown', max_digits=18)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, help_text='Reserved for orders (not yet shipped)', max_digits=18)),
                ('quantity_allocated', models.DecimalField(decimal_places=3, default=0, help_text='Allocated for current picking/processing', max_digits=18)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.stockbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.stockitem')),
                ('last_movement', models.ForeignKey(blank=True, help_text='Last movement that updated this balance (for idempotency)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_updates', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name_plural': 'Stock Balances',
                'indexes': [models.Index(fields=['company', 'item'], name='inventory_s_company_3b17dc_idx'), models.Index(fields=['company', 'godown', 'item'], name='inventory_s_company_df9153_idx'), models.Index(fields=['company', 'item', 'godown', 'batch'], name='inventory_s_company_d9080e_idx'), models.Index(fields=['company', 'created_at'], name='inventory_s_company_71c3ef_idx')],
                'unique_together': {('company', 'item', 'godown', 'batch')},
            },
        ),
    ]
