# Generated by Django 5.1.6 on 2025-12-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('inventory', '0002_stockbalance'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Portal product this stock item represents (for B2B catalog)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockitems', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'product'], name='inventory_s_company_f15d74_idx'),
        ),
    ]
