# Generated by Django 5.1.6 on 2025-12-26 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('inventory', '0003_stockitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Stock Categories',
                'indexes': [models.Index(fields=['company', 'is_active'], name='inventory_s_company_103c12_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.stockgroup')),
            ],
            options={
                'verbose_name_plural': 'Stock Groups',
                'indexes': [models.Index(fields=['company', 'is_active'], name='inventory_s_company_ce2c31_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity reserved', max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('reserved_for_type', models.CharField(blank=True, help_text="Type of entity this reservation is for (e.g., 'SalesOrder')", max_length=100)),
                ('reserved_for_id', models.IntegerField(blank=True, help_text='ID of the entity this reservation is for', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this reservation expires', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Stock Reservations',
                'indexes': [models.Index(fields=['company', 'item', 'status'], name='inventory_s_company_dc2724_idx'), models.Index(fields=['company', 'godown', 'status'], name='inventory_s_company_47bc39_idx'), models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx')],
            },
        ),
    ]
