# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('company', '0001_initial'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_departments', to='hr.department')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_exit', models.DateField(blank=True, help_text='Date when employee left', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_link', to='hr.employee')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_ledgers', to='accounting.ledger')),
            ],
            options={
                'verbose_name_plural': 'Employee Ledgers',
            },
        ),
        migrations.CreateModel(
            name='PayHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('pay_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement')], max_length=20)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this component is taxable')),
                ('is_fixed', models.BooleanField(default=True, help_text='Fixed amount vs percentage-based')),
                ('calculation_formula', models.TextField(blank=True, help_text='Formula for computation (if percentage-based)')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('ledger', models.ForeignKey(blank=True, help_text='Accounting ledger for this pay component', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_heads', to='accounting.ledger')),
            ],
            options={
                'verbose_name_plural': 'Pay Heads',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage value', max_digits=14)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='End date for this structure (null = current)', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_structure', to='hr.employee')),
                ('pay_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr.payhead')),
            ],
            options={
                'verbose_name_plural': 'Employee Pay Structures',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'January 2024 Payroll'", max_length=100)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('payment_date', models.DateField(help_text='Date when salaries will be paid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('POSTED', 'Posted to Accounts'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('voucher', models.OneToOneField(blank=True, help_text='Accounting voucher for this payroll', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Payroll Runs',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employee_code'], name='hr_employee_company_d36cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'department', 'is_active'], name='hr_employee_company_e58780_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'created_at'], name='hr_employee_company_1a75a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'code'], name='hr_departme_company_aa520a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'created_at'], name='hr_departme_company_631716_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='payhead',
            index=models.Index(fields=['company', 'code'], name='hr_payhead_company_2ac03c_idx'),
        ),
        migrations.AddIndex(
            model_name='payhead',
            index=models.Index(fields=['company', 'pay_type'], name='hr_payhead_company_d9dbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='payhead',
            index=models.Index(fields=['company', 'created_at'], name='hr_payhead_company_0c3bda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payhead',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='employeepaystructure',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employee_employe_1a00c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepaystructure',
            index=models.Index(fields=['pay_head', 'effective_from'], name='hr_employee_pay_hea_ea271e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'pay_period_start', 'pay_period_end'], name='hr_payrollr_company_ccdd30_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'status'], name='hr_payrollr_company_53f641_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'created_at'], name='hr_payrollr_company_916a4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('pay_period_start__lt', models.F('pay_period_end'))), name='payroll_period_start_before_end'),
        ),
    ]
