# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('POST', 'Posted'), ('CANCEL', 'Cancelled')], max_length=50)),
                ('object_type', models.CharField(help_text="Model name (e.g., 'Invoice', 'Voucher')", max_length=100)),
                ('object_id', models.UUIDField(help_text='UUID of the object')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of object', max_length=255)),
                ('changes', models.JSONField(default=dict, help_text='JSON diff of changes (before/after)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='system_audi_company_b299e2_idx'), models.Index(fields=['actor_user', 'created_at'], name='system_audi_actor_u_eb5fbb_idx'), models.Index(fields=['object_type', 'object_id'], name='system_audi_object__dcba8b_idx'), models.Index(fields=['action_type', 'created_at'], name='system_audi_action__3259f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Unique idempotency key from client', max_length=255, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to='company.company')),
                ('voucher', models.OneToOneField(help_text='Voucher created for this key', on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_record', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Idempotency Keys',
                'indexes': [models.Index(fields=['company', 'key'], name='system_idem_company_5d2d59_idx'), models.Index(fields=['company', 'created_at'], name='system_idem_company_0fcbf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, help_text="Type of event (e.g., 'invoice.created', 'order.updated')", max_length=100)),
                ('payload', models.JSONField(help_text='Event payload to send to external system')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry Scheduled')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of processing attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts before marking as failed')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Timestamp of last processing attempt', null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Scheduled time for next retry', null=True)),
                ('response', models.JSONField(blank=True, help_text='Response from external system', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('source_object_type', models.CharField(blank=True, help_text='Source model that triggered this event', max_length=100)),
                ('source_object_id', models.UUIDField(blank=True, help_text='UUID of source object', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when successfully processed', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Integration Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'next_retry_at'], name='system_inte_company_cb1c3b_idx'), models.Index(fields=['company', 'event_type'], name='system_inte_company_fa243f_idx'), models.Index(fields=['status', 'next_retry_at'], name='system_inte_status_46aef1_idx'), models.Index(fields=['source_object_type', 'source_object_id'], name='system_inte_source__da0b1a_idx'), models.Index(fields=['company', 'created_at'], name='system_inte_company_56f63f_idx'), models.Index(fields=['company', 'source_object_id'], name='system_inte_company_15ce07_idx')],
            },
        ),
    ]
