# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('nature', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('report_type', models.CharField(choices=[('BS', 'Balance Sheet'), ('PL', 'Profit & Loss')], max_length=10)),
                ('path', models.CharField(help_text='Materialized path for hierarchy traversal', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.accountgroup')),
            ],
            options={
                'verbose_name_plural': 'Account Groups',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Cost Centers',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('TAX', 'Tax'), ('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance amount', max_digits=16)),
                ('opening_balance_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], default='DR', max_length=2)),
                ('is_bill_wise', models.BooleanField(default=False, help_text='Enable bill-by-bill tracking (for receivables/payables)')),
                ('is_cost_center_applicable', models.BooleanField(default=False, help_text='Require cost center on entries')),
                ('requires_reconciliation', models.BooleanField(default=False, help_text='Enable bank reconciliation')),
                ('is_system', models.BooleanField(default=False, help_text='System-generated ledger (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounting.accountgroup')),
                ('opening_balance_fy', models.ForeignKey(help_text='Financial year for opening balance', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_opening_balances', to='company.financialyear')),
            ],
            options={
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='TaxLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('CGST', 'Central GST'), ('SGST', 'State GST'), ('IGST', 'Integrated GST'), ('VAT', 'VAT'), ('SERVICE_TAX', 'Service Tax'), ('TDS', 'TDS'), ('TCS', 'TCS')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage', max_digits=6)),
                ('tax_direction', models.CharField(choices=[('PAYABLE', 'Tax Payable (Output)'), ('RECEIVABLE', 'Tax Receivable (Input)')], max_length=10)),
                ('effective_from', models.DateField()),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='accounting.ledger')),
            ],
            options={
                'verbose_name_plural': 'Tax Ledgers',
            },
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['company', 'code'], name='accounting__company_6b4c96_idx'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['company', 'parent'], name='accounting__company_c407f5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['company', 'nature'], name='accounting__company_2090b8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['company', 'created_at'], name='accounting__company_6463cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountgroup',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'code'], name='accounting__company_aae4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_8efcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'created_at'], name='accounting__company_d39f68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'code'], name='accounting__company_8cd0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'account_type'], name='accounting__company_b8478f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_84e72b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company', 'created_at'], name='accounting__company_224bed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('company', 'code')},
        ),
    ]
