# Generated by Django 5.1.6 on 2025-12-25 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('company', '0002_alter_sequence_key'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_dr', models.DecimalField(decimal_places=2, default=0, help_text='Total debit balance', max_digits=24)),
                ('balance_cr', models.DecimalField(decimal_places=2, default=0, help_text='Total credit balance', max_digits=24)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('financial_year', models.ForeignKey(blank=True, help_text='Null means all-time balance (for non-FY specific queries)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_balances', to='company.financialyear')),
                ('last_posted_voucher', models.ForeignKey(blank=True, help_text='Last posted voucher that updated this balance (for idempotency)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_updates', to='voucher.voucher')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounting.ledger')),
            ],
            options={
                'verbose_name_plural': 'Ledger Balances',
                'indexes': [models.Index(fields=['company', 'ledger'], name='accounting__company_5a0ff0_idx'), models.Index(fields=['company', 'financial_year', 'ledger'], name='accounting__company_2f4624_idx'), models.Index(fields=['company', 'ledger', 'financial_year'], name='accounting__company_c4e030_idx'), models.Index(fields=['company', 'created_at'], name='accounting__company_da5405_idx')],
                'unique_together': {('company', 'ledger', 'financial_year')},
            },
        ),
    ]
