# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('invoice', '0001_initial'),
        ('orders', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, help_text='GST Number for transporter', max_length=15)),
                ('transport_id', models.CharField(blank=True, help_text='Transporter ID for e-way bill', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Carriers',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(db_index=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, help_text="Carrier's tracking number", max_length=100)),
                ('shipped_date', models.DateField()),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready to Ship'), ('PICKED', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('eway_bill_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='logistics.carrier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='company.address')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='invoice.invoice')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.salesorder')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='party.partyaddress')),
            ],
            options={
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('package_number', models.CharField(blank=True, help_text='Package/box number if multiple packages', max_length=50)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.stockbatch')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='invoice.invoiceline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.stockitem')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipment')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Shipment Items',
                'ordering': ['shipment', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['company', 'code'], name='logistics_c_company_a38bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['company', 'is_active'], name='logistics_c_company_876989_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['company', 'created_at'], name='logistics_c_company_0346d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrier',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'shipment_number'], name='logistics_s_company_58fe4f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'status'], name='logistics_s_company_a54545_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'shipped_date'], name='logistics_s_company_c25941_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sales_order'], name='logistics_s_sales_o_27ae85_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['invoice'], name='logistics_s_invoice_f12ede_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['company', 'created_at'], name='logistics_s_company_c51179_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('company', 'shipment_number')},
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'line_no'], name='logistics_s_shipmen_ec5109_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['item'], name='logistics_s_item_id_711c39_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shipment_item_quantity_positive'),
        ),
    ]
