# Generated by Django 5.1.6 on 2026-02-07 08:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_seed_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Tax name (e.g., 'GST 18%', 'Service Tax')", max_length=200)),
                ('computation', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', help_text='Percentage or fixed amount computation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tax rate percentage or fixed amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this tax currently active?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='pricing_tax_company_2472dd_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
