# Generated by Django 5.1.6 on 2026-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_make_phoneotp_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(default='REGISTRATION', help_text='Purpose of OTP: REGISTRATION, LOGIN, etc.', max_length=50),
        ),
    ]
