# Generated by Django 5.1.6 on 2025-12-26 14:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_ledgerbalance'),
        ('company', '0002_alter_sequence_key'),
        ('invoice', '0004_add_payment_models_and_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGSTSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_summary', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice GST Summary',
                'verbose_name_plural': 'Invoice GST Summaries',
            },
        ),
        migrations.CreateModel(
            name='GSTLedgerMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('CGST', 'CGST Output'), ('SGST', 'SGST Output'), ('IGST', 'IGST Output'), ('CGST_INPUT', 'CGST Input'), ('SGST_INPUT', 'SGST Input'), ('IGST_INPUT', 'IGST Input')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_mappings', to='accounting.ledger')),
            ],
            options={
                'verbose_name': 'GST Ledger Mapping',
                'verbose_name_plural': 'GST Ledger Mappings',
                'unique_together': {('company', 'tax_type')},
            },
        ),
        migrations.CreateModel(
            name='GSTR1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('outward_taxable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'GSTR-1',
                'verbose_name_plural': 'GSTR-1 Returns',
                'indexes': [models.Index(fields=['company', 'period'], name='gst_gstr1_company_685e89_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GSTR3B',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('outward_taxable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('inward_itc_cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('inward_itc_sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('inward_itc_igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cgst_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('sgst_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('igst_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'GSTR-3B',
                'verbose_name_plural': 'GSTR-3B Returns',
                'indexes': [models.Index(fields=['company', 'period'], name='gst_gstr3b_company_4fee6b_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
    ]
