# Generated by Django 5.1.6 on 2025-12-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockbalance'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the order was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the order was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When the order was posted to accounting', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='Price list for this order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.pricelist'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20),
        ),
    ]
