# Generated by Django 5.1.6 on 2025-12-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, help_text='When the order was invoiced', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL_INVOICED', 'Partially Invoiced'), ('INVOICE_CREATED_PENDING_POSTING', 'Invoice Created Pending Posting'), ('INVOICED', 'Invoiced'), ('PARTIAL_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL_INVOICED', 'Partially Invoiced'), ('INVOICE_CREATED_PENDING_POSTING', 'Invoice Created Pending Posting'), ('INVOICED', 'Invoiced'), ('PARTIAL_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=40),
        ),
    ]
