# Generated by Django 6.0.1 on 2026-02-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('orders', '0004_salesorder_invoiced_at_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Employee assigned for delivery/processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='hr.employee'),
        ),
    ]
