# Generated by Django 5.1.6 on 2025-12-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, help_text='Currently selected company for this user session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='company.company'),
        ),
    ]
