# Generated by Django 5.1.6 on 2026-01-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
