# Generated by Django 5.1.6 on 2026-02-07 07:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_seed_currencies'),
        ('inventory', '0004_stockcategory_stockgroup_stockreservation'),
        ('invoice', '0005_invoice_billing_period_end_and_more'),
        ('party', '0003_allow_nullable_ledger'),
        ('products', '0002_product_has_variants_product_is_subscribable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Discount name (e.g., 'Summer Sale 20%', 'New Customer $50 Off')", max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Unique discount code (auto-generated if blank)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Discount description')),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], help_text='Fixed amount or percentage discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (amount or percentage)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum purchase amount required', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='Minimum quantity required')),
                ('max_usage_per_customer', models.PositiveIntegerField(default=0, help_text='Max uses per customer (0 = unlimited)')),
                ('max_total_usage', models.PositiveIntegerField(default=0, help_text='Max total uses across all customers (0 = unlimited)')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Current usage count')),
                ('start_date', models.DateField(db_index=True, help_text='Discount becomes valid from this date')),
                ('end_date', models.DateField(db_index=True, help_text='Discount expires after this date')),
                ('applies_to_products', models.BooleanField(default=True, help_text='Can be applied to product purchases')),
                ('applies_to_subscriptions', models.BooleanField(default=True, help_text='Can be applied to subscriptions')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this discount currently active?')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Specific products this discount applies to (empty = all products)', related_name='discount_rules', to='products.product')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Attribute name (e.g., 'Size', 'Color', 'Material')", max_length=100)),
                ('values', models.JSONField(default=list, help_text="List of possible values: ['S', 'M', 'L'] or ['Red', 'Blue']")),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order on product page')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - unique identifier for this variant', max_length=100, unique=True)),
                ('attributes', models.JSONField(default=dict, help_text='Attribute values: {"Size": "M", "Color": "Red"}')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this variant', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_adjustments', models.JSONField(blank=True, default=dict, help_text='Price adjustments per attribute: {"Size": 50, "Color": 100}')),
                ('display_name', models.CharField(blank=True, help_text='Display name override (auto-generated if blank)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this variant available for sale?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('stock_item', models.ForeignKey(blank=True, help_text='Link to inventory tracking (if physical product)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(db_index=True, help_text='Unique quotation identifier (auto-generated)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', help_text='Quotation status', max_length=20)),
                ('valid_until', models.DateField(db_index=True, help_text='Quotation expiry date')),
                ('start_date', models.DateField(help_text='Proposed subscription start date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total quoted amount', max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When quotation was sent to customer', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When customer accepted quotation', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When customer rejected quotation', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Quotation terms and conditions')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='company.currency')),
                ('party', models.ForeignKey(help_text='Customer receiving the quotation', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='party.party')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='subscriptions.productvariant')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.quotation')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Number of days quotation is valid (from creation)')),
                ('default_terms_and_conditions', models.TextField(blank=True, help_text='Default T&C to include in quotations')),
                ('template_content', models.JSONField(blank=True, default=dict, help_text='Additional template configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Quotation Template',
                'verbose_name_plural': 'Quotation Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='subscriptions.quotationtemplate'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_number', models.CharField(db_index=True, help_text='Unique subscription identifier (auto-generated)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUOTATION', 'Quotation Sent'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', help_text='Current subscription state', max_length=20)),
                ('start_date', models.DateField(db_index=True, help_text='Subscription start date')),
                ('end_date', models.DateField(blank=True, help_text='Subscription end date (null = no end date)', null=True)),
                ('next_billing_date', models.DateField(db_index=True, help_text='Next scheduled billing date')),
                ('last_billing_date', models.DateField(blank=True, help_text='Last invoice generation date', null=True)),
                ('billing_cycle_count', models.PositiveIntegerField(default=0, help_text='Number of billing cycles completed')),
                ('monthly_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Normalized monthly recurring revenue (MRR)', max_digits=14)),
                ('discount_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], help_text='Discount type: Fixed or Percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount or percentage value', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_start', models.DateField(blank=True, help_text='Discount validity start date', null=True)),
                ('discount_end', models.DateField(blank=True, help_text='Discount validity end date', null=True)),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('payment_method', models.CharField(blank=True, help_text="Payment method used (e.g., 'Credit Card', 'Bank Transfer', 'Cash')", max_length=100)),
                ('payment_done', models.BooleanField(default=False, help_text='Whether payment has been completed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When subscription was confirmed', null=True)),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, help_text='When subscription became active', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When subscription was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When subscription was closed', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Subscription terms and conditions')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='company.currency')),
                ('party', models.ForeignKey(help_text='Customer/subscriber', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='party.party')),
                ('quotation_template', models.ForeignKey(blank=True, help_text='Quotation template used for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_using_template', to='subscriptions.quotationtemplate')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text='Subscription created from this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=14)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original amount before discount', max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount after discount', max_digits=14)),
                ('applied_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When discount was applied')),
                ('applied_by', models.ForeignKey(blank=True, help_text='User who applied the discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_discounts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice this discount was applied to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='invoice.invoice')),
                ('party', models.ForeignKey(help_text='Customer who received the discount', on_delete=django.db.models.deletion.PROTECT, related_name='discount_applications', to='party.party')),
                ('discount_rule', models.ForeignKey(help_text='Discount rule that was applied', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='subscriptions.discountrule')),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription this discount was applied to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Discount Application',
                'verbose_name_plural': 'Discount Applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity per billing cycle', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line-level discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax rate percentage', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Custom description (overrides product description)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Specific variant if product has variants', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='subscriptions.productvariant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Plan display name (e.g., 'Premium Monthly', 'Enterprise Annual')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed plan description for customers')),
                ('billing_interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='How often to bill: Daily/Weekly/Monthly/Quarterly/Yearly', max_length=20)),
                ('billing_interval_count', models.PositiveIntegerField(default=1, help_text='Billing frequency multiplier (e.g., 2 = every 2 months)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base subscription price per billing cycle', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time setup fee charged on first billing', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Number of days for free trial (0 = no trial)')),
                ('is_auto_closable', models.BooleanField(default=False, help_text='Automatically close after end_date')),
                ('is_closable', models.BooleanField(default=True, help_text='Can be manually closed by user')),
                ('is_pausable', models.BooleanField(default=True, help_text='Can be paused/suspended temporarily')),
                ('is_renewable', models.BooleanField(default=True, help_text='Can be renewed after expiration')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity required per product')),
                ('start_date', models.DateField(blank=True, help_text='Plan becomes available from this date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Plan no longer available after this date', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this plan currently available for new subscriptions?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='Subscription plan template', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='plan',
            field=models.ForeignKey(help_text='Default subscription plan for this template', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='plan',
            field=models.ForeignKey(help_text='Proposed subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='subscriptions.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PlanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Quantity included per billing cycle', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (overrides product default)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_memberships', to='products.product')),
                ('product_variant', models.ForeignKey(blank=True, help_text='Specific variant if product has variants', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_memberships', to='subscriptions.productvariant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_products', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['company', 'is_active', 'start_date', 'end_date'], name='subscriptio_company_7894c6_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['code'], name='subscriptio_code_137981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountrule',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['company', 'product'], name='subscriptio_company_498f65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'name')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['company', 'product', 'is_active'], name='subscriptio_company_843e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='subscriptio_sku_51aa41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'attributes')},
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['company', 'party', 'applied_on'], name='subscriptio_company_b43e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['company', 'discount_rule'], name='subscriptio_company_69b88a_idx'),
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['applied_on'], name='subscriptio_applied_f1892d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['company', 'is_active'], name='subscriptio_company_f9754e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['company', 'billing_interval'], name='subscriptio_company_359258_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='subscriptio_company_d594e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'status', 'next_billing_date'], name='subscriptio_company_938786_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'party', 'status'], name='subscriptio_company_6b98f2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'start_date'], name='subscriptio_company_15fe73_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_billing_date', 'status'], name='subscriptio_next_bi_321933_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_number'], name='subscriptio_subscri_c33376_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('company', 'subscription_number')},
        ),
        migrations.AddIndex(
            model_name='quotationtemplate',
            index=models.Index(fields=['company', 'is_active'], name='subscriptio_company_643337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotationtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'status', 'valid_until'], name='subscriptio_company_67cf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'party', 'status'], name='subscriptio_company_f66fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='subscriptio_quotati_da7ce7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('company', 'quotation_number')},
        ),
        migrations.AlterUniqueTogether(
            name='planproduct',
            unique_together={('plan', 'product', 'product_variant')},
        ),
    ]
