# Generated by Django 5.1.6 on 2026-02-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_assigned_user_product_cost_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this attribute belongs to. Null for global attributes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product'),
        ),
    ]
