# Generated by Django 5.1.6 on 2026-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Payment terms and conditions', null=True),
        ),
    ]
