# Generated by Django 5.1.6 on 2025-12-26 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(help_text='Type of object (voucher, order, invoice, etc.)', max_length=50)),
                ('target_id', models.UUIDField(help_text='ID of the object requiring approval')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Approval/rejection remarks')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of approval/rejection', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected (Checker)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('requested_by', models.ForeignKey(help_text='User who requested approval (Maker)', on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'indexes': [models.Index(fields=['company', 'target_type', 'target_id'], name='workflow_ap_company_b7888d_idx'), models.Index(fields=['company', 'status'], name='workflow_ap_company_40fced_idx'), models.Index(fields=['requested_by'], name='workflow_ap_request_972121_idx'), models.Index(fields=['approved_by'], name='workflow_ap_approve_4321d6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('company', 'target_type', 'target_id'), name='one_pending_approval_per_target')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(help_text='Type of object (voucher, order, invoice)', max_length=50)),
                ('approval_required', models.BooleanField(default=True, help_text='Whether approval is mandatory')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approval required if amount exceeds this', max_digits=16, null=True)),
                ('auto_approve_below_threshold', models.BooleanField(default=False, help_text='Auto-approve if below threshold')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'unique_together': {('company', 'target_type')},
            },
        ),
    ]
