# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('JOURNAL', 'Journal'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('DEBIT_NOTE', 'Debit Note'), ('CREDIT_NOTE', 'Credit Note')], max_length=30)),
                ('is_accounting', models.BooleanField(default=True, help_text='Posts to accounting ledgers')),
                ('is_inventory', models.BooleanField(default=False, help_text='Affects inventory (stock movements)')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Voucher Types',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('narration', models.TextField(blank=True, help_text='Description/remarks for the voucher')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice #, cheque #, etc.)', max_length=50)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='company.financialyear')),
                ('reversed_voucher', models.ForeignKey(blank=True, help_text='If this is a reversal, link to original voucher', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='voucher.voucher')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='voucher.vouchertype')),
            ],
            options={
                'verbose_name_plural': 'Vouchers',
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(help_text='Line number for ordering')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('entry_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('against_voucher', models.ForeignKey(blank=True, help_text='For bill-wise accounting (receivables/payables)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_lines', to='voucher.voucher')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.costcenter')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Voucher Lines',
                'ordering': ['voucher', 'line_no'],
                'indexes': [models.Index(fields=['voucher', 'line_no'], name='voucher_vou_voucher_1ab152_idx'), models.Index(fields=['ledger', 'entry_type'], name='voucher_vou_ledger__42f96a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('entry_type__in', ['DR', 'CR'])), name='valid_dr_cr'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='voucher_line_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['company', 'code'], name='voucher_vou_company_8ce529_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['company', 'category'], name='voucher_vou_company_b0052e_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertype',
            index=models.Index(fields=['company', 'created_at'], name='voucher_vou_company_7bd9e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchertype',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_number'], name='voucher_vou_company_663f77_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'date', 'status'], name='voucher_vou_company_6f79af_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_type', 'status'], name='voucher_vou_company_d65b94_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'financial_year'], name='voucher_vou_company_422a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'created_at'], name='voucher_vou_company_93c668_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'status'], name='voucher_vou_company_292c4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('company', 'voucher_type', 'financial_year', 'voucher_number'), name='unique_voucher_per_company_type_fy'),
        ),
    ]
