# Generated by Django 5.1.6 on 2025-12-25 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ledgerbalance'),
        ('company', '0002_alter_sequence_key'),
        ('invoice', '0004_add_payment_models_and_posted_at'),
        ('party', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when voucher was posted', null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque/transfer reference', max_length=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(help_text='Bank/cash ledger for payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('party', models.ForeignKey(blank=True, help_text='Party for advance payments without invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='party.party')),
                ('posted_voucher', models.ForeignKey(blank=True, help_text='Posted voucher reference', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_payments', to='voucher.voucher')),
                ('voucher', models.OneToOneField(help_text='Associated voucher for posting', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Amount applied to this invoice or advance', max_digits=16)),
                ('line_no', models.PositiveIntegerField(help_text='Line number in payment')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice being paid (null for advance)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_lines', to='invoice.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='voucher.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Lines',
                'ordering': ['payment', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='voucher_pay_company_c546af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status'], name='voucher_pay_company_3da8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'party'], name='voucher_pay_company_245f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentline',
            index=models.Index(fields=['payment', 'line_no'], name='voucher_pay_payment_b5fc19_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentline',
            index=models.Index(fields=['invoice'], name='voucher_pay_invoice_74b20c_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_applied__gt', 0)), name='payment_line_amount_positive'),
        ),
    ]
