# Generated by Django 5.1.6 on 2025-12-25 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_add_payment_models_and_posted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason for reversal'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_user',
            field=models.ForeignKey(blank=True, help_text='User who reversed this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when voucher was reversed', null=True),
        ),
    ]
