# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('PRIVATE_LIMITED', 'Private Limited'), ('PUBLIC_LIMITED', 'Public Limited'), ('PARTNERSHIP', 'Partnership'), ('PROPRIETORSHIP', 'Proprietorship'), ('LLP', 'Limited Liability Partnership')], default='PRIVATE_LIMITED', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_enabled', models.BooleanField(default=True)),
                ('accounting_enabled', models.BooleanField(default=True)),
                ('payroll_enabled', models.BooleanField(default=False)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False, help_text='When locked, no financial transactions can be modified')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company Features',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='company.currency'),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False, help_text='Once closed, no transactions can be posted to this FY')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Financial Years',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Unique identifier like VOUCHER, INVOICE, SO, PO', max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('reset_period', models.CharField(choices=[('NEVER', 'Never Reset'), ('YEARLY', 'Reset Yearly'), ('MONTHLY', 'Reset Monthly'), ('DAILY', 'Reset Daily')], default='YEARLY', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Sequences',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('REGISTERED', 'Registered Office'), ('CORPORATE', 'Corporate Office'), ('BRANCH', 'Branch'), ('WAREHOUSE', 'Warehouse'), ('BILLING', 'Billing'), ('SHIPPING', 'Shipping')], max_length=30)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['company', 'address_type'], name='company_add_company_ecf740_idx'), models.Index(fields=['company', 'created_at'], name='company_add_company_c6b360_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('STOCK_KEEPER', 'Stock Keeper'), ('SALES', 'Sales Person'), ('VIEWER', 'View Only')], default='VIEWER', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Default company when user logs in')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Users',
                'indexes': [models.Index(fields=['company', 'is_active'], name='company_com_company_22d671_idx'), models.Index(fields=['user', 'is_default'], name='company_com_user_id_8e3186_idx'), models.Index(fields=['company', 'created_at'], name='company_com_company_b09ef0_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='company_com_code_ee287f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'is_deleted'], name='company_com_is_acti_c3ff55_idx'),
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['company', 'is_current'], name='company_fin_company_8c7c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='company_fin_company_a96b41_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('company',), name='one_current_fy_per_company'),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='fy_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['company', 'key'], name='company_seq_company_141cb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('company', 'key')},
        ),
    ]
