# Generated by Django 5.1.6 on 2025-12-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='key',
            field=models.CharField(help_text='Unique identifier or compound key (company_id:code:fy_id)', max_length=100),
        ),
    ]
