# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for this retailer')),
                ('can_place_orders', models.BooleanField(default=True, help_text='Permission to create orders')),
                ('can_view_balance', models.BooleanField(default=True, help_text='Permission to view account balance')),
                ('can_view_statements', models.BooleanField(default=True, help_text='Permission to view ledger statements')),
                ('party', models.ForeignKey(help_text='Business party this user represents', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_users', to='party.party')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retailer User',
                'verbose_name_plural': 'Retailer Users',
            },
        ),
        migrations.CreateModel(
            name='RetailerCompanyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this access request')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retailer_accesses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_accesses', to='company.company')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to='portal.retaileruser')),
            ],
            options={
                'verbose_name': 'Retailer Company Access',
                'verbose_name_plural': 'Retailer Company Accesses',
            },
        ),
        migrations.AddIndex(
            model_name='retaileruser',
            index=models.Index(fields=['party'], name='portal_reta_party_i_4dc6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='retaileruser',
            index=models.Index(fields=['is_primary_contact'], name='portal_reta_is_prim_2a5319_idx'),
        ),
        migrations.AddIndex(
            model_name='retailercompanyaccess',
            index=models.Index(fields=['retailer', 'status'], name='portal_reta_retaile_bc1bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='retailercompanyaccess',
            index=models.Index(fields=['company', 'status'], name='portal_reta_company_c660f2_idx'),
        ),
        migrations.AddIndex(
            model_name='retailercompanyaccess',
            index=models.Index(fields=['status'], name='portal_reta_status_715d24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retailercompanyaccess',
            unique_together={('retailer', 'company')},
        ),
    ]
