# Generated by Django 5.1.6 on 2025-12-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_retaileruser'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retaileruser',
            name='party',
            field=models.ForeignKey(help_text='Business party this user represents', on_delete=django.db.models.deletion.CASCADE, related_name='portal_retailer_users', to='party.party'),
        ),
    ]
