# Generated by Django 6.0.1 on 2026-02-05 19:57

import django.db.models.deletion
from django.db import migrations, models


def cleanup_orphaned_retailer_access(apps, schema_editor):
    """
    Remove RetailerCompanyAccess records that reference non-existent party.RetailerUser records.
    This is needed because we're changing the FK target from portal.RetailerUser to party.RetailerUser.
    """
    RetailerCompanyAccess = apps.get_model('portal', 'RetailerCompanyAccess')
    PartyRetailerUser = apps.get_model('party', 'RetailerUser')
    
    # Get all valid retailer user IDs from party app
    valid_retailer_ids = set(PartyRetailerUser.objects.values_list('id', flat=True))
    
    # Delete access records with invalid retailer references
    orphaned = RetailerCompanyAccess.objects.exclude(retailer_id__in=valid_retailer_ids)
    count = orphaned.count()
    if count > 0:
        orphaned.delete()
        print(f"Cleaned up {count} orphaned RetailerCompanyAccess record(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_allow_nullable_ledger'),
        ('portal', '0002_alter_retaileruser_party'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_retailer_access,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='retailercompanyaccess',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to='party.retaileruser'),
        ),
    ]
