# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Both Customer & Supplier'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15)),
                ('pan', models.CharField(blank=True, help_text='PAN Number', max_length=10)),
                ('is_retailer', models.BooleanField(default=False, help_text='Enable portal login for this party')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed', max_digits=14)),
                ('credit_days', models.PositiveIntegerField(default=0, help_text='Payment terms in days')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('ledger', models.OneToOneField(help_text='Associated accounting ledger', on_delete=django.db.models.deletion.PROTECT, related_name='party', to='accounting.ledger')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('REGISTERED', 'Registered Office'), ('CONTACT', 'Contact')], max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default address for this type')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='party.party')),
            ],
            options={
                'verbose_name_plural': 'Party Addresses',
            },
        ),
        migrations.CreateModel(
            name='PartyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc', models.CharField(help_text='IFSC Code (for Indian banks)', max_length=20)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code (for international)', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for payments')),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='party.party')),
            ],
            options={
                'verbose_name_plural': 'Party Bank Accounts',
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'party_type'], name='party_party_company_4939de_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'is_active'], name='party_party_company_fea678_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'gstin'], name='party_party_company_ce8184_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'created_at'], name='party_party_company_44c593_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaddress',
            index=models.Index(fields=['party', 'address_type'], name='party_party_party_i_22e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='partybankaccount',
            index=models.Index(fields=['party', 'is_primary'], name='party_party_party_i_7b6407_idx'),
        ),
    ]
