# Generated by Django 5.1.6 on 2025-12-26 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Supplier/manufacturer company being accessed', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_users', to='company.company')),
                ('party', models.ForeignKey(blank=True, help_text='Associated party record (customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_users', to='party.party')),
                ('user', models.ForeignKey(help_text='The retailer user account', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='party_retai_user_id_f2fc68_idx'), models.Index(fields=['company', 'status'], name='party_retai_company_89d568_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
