# Generated by Django 6.0.1 on 2026-02-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ledgerbalance'),
        ('party', '0002_retaileruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='ledger',
            field=models.OneToOneField(blank=True, help_text='Associated accounting ledger', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party', to='accounting.ledger'),
        ),
    ]
