# Generated by Django 5.1.6 on 2025-12-26 13:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Category name (e.g., 'Cement', 'Steel TMT Bars')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Category description for portal display')),
                ('is_active', models.BooleanField(default=True, help_text='Show in portal catalog')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in catalog')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Product display name for portal', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description for portal')),
                ('brand', models.CharField(blank=True, help_text="Brand name (e.g., 'Asian Paints', 'Tata Steel')", max_length=100)),
                ('available_quantity', models.PositiveIntegerField(default=0, help_text='Display quantity (aggregated from stock items)')),
                ('unit', models.CharField(choices=[('BAG', 'Bags'), ('BAL', 'Bale'), ('BDL', 'Bundles'), ('BKL', 'Buckles'), ('BOU', 'Billions of Units'), ('BOX', 'Box'), ('BTL', 'Bottles'), ('BUN', 'Bunches'), ('CAN', 'Cans'), ('CBM', 'Cubic Meter'), ('CCM', 'Cubic Centimeter'), ('CMS', 'Centimeters'), ('CTN', 'Cartons'), ('DOZ', 'Dozens'), ('DRM', 'Drums'), ('GGK', 'Great Gross'), ('GMS', 'Grams'), ('GRS', 'Gross'), ('GYD', 'Gross Yards'), ('KGS', 'Kilograms'), ('KLR', 'Kilolitre'), ('KME', 'Kilometre'), ('LTR', 'Litre'), ('MTR', 'Meters'), ('MLT', 'Millilitre'), ('MTS', 'Metric Ton'), ('NOS', 'Numbers'), ('PAC', 'Packs'), ('PCS', 'Pieces'), ('PRS', 'Pairs'), ('QTL', 'Quintal'), ('ROL', 'Rolls'), ('SET', 'Sets'), ('SQF', 'Square Feet'), ('SQM', 'Square Meter'), ('SQY', 'Square Yards'), ('TBS', 'Tablets'), ('TGM', 'Ten Grams'), ('THD', 'Thousands'), ('TON', 'Tonne'), ('TUB', 'Tubes'), ('UGS', 'US Gallons'), ('UNT', 'Units'), ('YDS', 'Yards')], default='PCS', help_text='Display unit for portal (actual UOM in StockItem)', max_length=10)),
                ('total_shipped', models.PositiveIntegerField(default=0, help_text='Total quantity shipped (legacy field)')),
                ('total_required_quantity', models.PositiveIntegerField(default=0, help_text='Total required quantity (legacy field)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Display price (MRP or list price)', max_digits=10)),
                ('hsn_code', models.CharField(default='0000', help_text='HSN/SAC code for GST', max_length=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST rate percentage', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST rate percentage', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST rate percentage', max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cess rate percentage', max_digits=5)),
                ('is_portal_visible', models.BooleanField(default=True, help_text='Show in retailer portal catalog')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage/promotions')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('on_demand', 'On Demand'), ('discontinued', 'Discontinued')], default='available', help_text='Product availability status', max_length=20)),
                ('category', models.ForeignKey(blank=True, help_text='Product category for browsing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'is_active', 'display_order'], name='products_ca_company_1a4e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'name'], name='products_ca_company_14f238_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'created_at'], name='products_ca_company_4edaef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'category', 'is_portal_visible'], name='products_pr_company_02cd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_portal_visible', 'status'], name='products_pr_company_a0a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'brand'], name='products_pr_company_430082_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'hsn_code'], name='products_pr_company_063f03_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'name'], name='products_pr_company_28b2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'created_at'], name='products_pr_company_fe4c69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
