# Generated by Django 5.1.6 on 2026-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(db_index=True, default=False, help_text='Does this product have attribute-based variants?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_subscribable',
            field=models.BooleanField(db_index=True, default=False, help_text='Can this product be sold via subscription?'),
        ),
    ]
