# Generated by Django 5.1.6 on 2026-02-07 08:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_seed_currencies'),
        ('products', '0002_product_has_variants_product_is_subscribable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='User assigned to manage this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price of the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service'), ('CONSUMABLE', 'Consumable')], default='GOODS', help_text='Type of product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage', max_digits=5),
        ),
        migrations.CreateModel(
            name='ProductRecurringPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurring_plan', models.CharField(help_text="Name of the recurring plan (e.g., 'Monthly', 'Quarterly')", max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this recurring plan', max_digits=10)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Minimum quantity for this price')),
                ('start_date', models.DateField(blank=True, help_text='Date when this pricing becomes effective', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date when this pricing expires', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('product', models.ForeignKey(help_text='Product this pricing applies to', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Recurring Price',
                'verbose_name_plural': 'Product Recurring Prices',
                'ordering': ['recurring_plan', 'min_qty'],
                'indexes': [models.Index(fields=['company', 'product'], name='products_pr_company_14be96_idx'), models.Index(fields=['product', 'recurring_plan'], name='products_pr_product_455a3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.CharField(help_text="Variant attribute name (e.g., 'Size', 'Color')", max_length=100)),
                ('values', models.CharField(help_text="Comma-separated variant values (e.g., 'Small,Medium,Large')", max_length=255)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional price for this variant', max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('product', models.ForeignKey(help_text='Product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['attribute'],
                'indexes': [models.Index(fields=['company', 'product'], name='products_pr_company_e8aa9f_idx'), models.Index(fields=['product', 'attribute'], name='products_pr_product_91ee1d_idx')],
            },
        ),
    ]
