# Generated by Django 5.1.6 on 2025-12-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('party', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_type', models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('DEBIT_NOTE', 'Debit Note'), ('CREDIT_NOTE', 'Credit Note'), ('PROFORMA', 'Proforma Invoice')], max_length=20)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='company.currency')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='company.financialyear')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='party.party')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.salesorder')),
                ('voucher', models.OneToOneField(blank=True, help_text='Accounting voucher generated from this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='voucher.voucher')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(help_text='Line number in invoice')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Line total after discount before tax', max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.stockitem')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['invoice', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_number'], name='invoice_inv_company_942f29_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'party', 'status'], name='invoice_inv_company_cd3d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_date'], name='invoice_inv_company_7d4bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'due_date'], name='invoice_inv_company_b41980_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_type', 'status'], name='invoice_inv_company_9baefb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'created_at'], name='invoice_inv_company_d4989d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='invoice_inv_company_1ebfa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'line_no'], name='invoice_inv_invoice_1c194c_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_line_quantity_positive'),
        ),
    ]
