# Generated by Django 5.1.6 on 2025-12-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_sequence_key'),
        ('invoice', '0002_remove_invoiceline_tax_rate_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='financial_year',
            field=models.ForeignKey(blank=True, help_text='Financial year is resolved by posting engine', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='company.financialyear'),
        ),
    ]
