# Generated by Django 5.1.6 on 2025-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_make_financial_year_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount received against this invoice', max_digits=16),
        ),
    ]
