# Generated by Django 5.1.6 on 2026-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_add_payment_models_and_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, db_index=True, help_text='Billing period end date (for subscription invoices)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, db_index=True, help_text='Billing period start date (for subscription invoices)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='Was this invoice auto-generated by subscription billing?'),
        ),
    ]
