# Generated by Django 5.1.6 on 2026-02-07 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_billing_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', help_text='Payment method', max_length=50)),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction/cheque reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice', 'payment_date'], name='invoice_inv_invoice_94015b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_payment_amount_positive')],
            },
        ),
    ]
